baseURL = "https://acjoshi.dev/"
languageCode = "en-us"
title = "Atharva CJ's place"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "toothsy"
  description = "If that is our will, who dares to stop us?"
  github = "toothsy"
  tumblr = "dootdootdootdootdootdootdoot"
  email = "c.j.atharva@gmail.com"
  keywords = "blog, google analytics"
  rss = true
  lastmod = false
  favicon = "/images/github-mark.png"
  avatar = "/images/thorfinn.jpeg"
  headerIcon = "/images/github-mark-white.png"
  location = "India"
  userStatusEmoji = "ğŸ˜"
  enableGitalk = false
  enableSearch = false
  bluesky = "cjatharva.bsky.social"

  [params.gitalk]
    clientID = "Your client ID" # Your client ID
    clientSecret = "Your client secret" # Your client secret
    repo = "LuvSia" # æ‚¨çš„åšå®¢çš„githubåœ°å€Repository nameï¼Œä¾‹å¦‚ï¼šxxxx.github.io
    owner = "ventusoon" # æ‚¨çš„GitHub ID
    admin = "ventusoon" # æ‚¨çš„GitHub ID
    id = "location.pathname" # æ–‡ç« é¡µé¢çš„é“¾æ¥åœ°å€å°±æ˜¯ID
    labels = "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage = 15 # Pagination size, with maximum 100.
    pagerDirection = "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually = true # è®¾ç½®ä¸ºtrueï¼Œå¦‚æœæ˜¯ç®¡ç†å‘˜ç™»å½•ï¼Œä¼šè‡ªåŠ¨åˆ›å»ºissueï¼Œå¦‚æœæ˜¯falseï¼Œéœ€è¦ç®¡ç†å‘˜æ‰‹åŠ¨æ·»åŠ ç¬¬ä¸€ä¸ªè¯„è®º(issue)
    distractionFreeMode = false # Enable hot key (cmd|ctrl + enter) submit comment.
    proxy = "https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token" # å¯ä»¥è‡ªè¡Œæ·»åŠ åå‘ä»£ç†


[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]


